using System;
using System.Runtime.InteropServices;
using System.IO;
using System.Text;
using Utils;
using static System.Console;

public static class Program
{
    public static void Main(string[] args) 
    {
          var defaultMessage = "\n\n\n \tHello From the Other Side!";
          var bot = GetBot();
          var (message, withColor) = ParseArgs(args);
          var output = message == string.Empty ? $"    {defaultMessage}{bot}" : $"    {message}{bot}";

          if (withColor)
          {
              ConsoleUtils.PrintStringWithRandomColor(output);
          }
          else
          {
              WriteLine(output);
          }
          
          WriteLine("**Environment**");
          WriteLine($"Platform: .NET Framework");
          WriteLine($"OS: {RuntimeInformation.OSDescription}");
        WriteLine();
        ReadKey();
    }

    private static (string, bool) ParseArgs(string[] args)
    {
      var buffer = new StringBuilder();
      var withColor = true;
      foreach(var s in args)
      {
        if (s == "--with-color")
        {
          withColor = true;
          continue;
        }
        buffer.Append(" ");
        buffer.Append(s);
      }

      return (buffer.ToString(), withColor);
    }

    private static string GetBot() 
    {
            
            return @"
      __________________
                        \
                        \
                            ....
                            ....'
                            ....
                          ..........
                      .............'..'..
                  ................'..'.....
                .......'..........'..'..'....
                ........'..........'..'..'.....
              .'....'..'..........'..'.......'.
              .'..................'...   ......
              .  ......'.........         .....
              .                           ......
              ..    . ALPHA BOLD ..       ......
            ....       .                 .......
            ......  .......          ............
              ................  ......................
              ........................'................
            ......................'..'......    .......
          .........................'..'.....       .......
      ........    ..'.............'..'....      ..........
    ..'..'...      ...............'.......      ..........
    ...'......     ...... ..........  ......         .......
  ...........   .......              ........        ......
  .......        '...'.'.              '.'.'.'         ....
  .......       .....'..               ..'.....
    ..       ..........               ..'........
            ............               ..............
          .............               '..............
          ...........'..              .'.'............
        ...............              .'.'.............
        .............'..               ..'..'...........
        ...............                 .'..............
        .........                        ..............
          .....

  ";
    }
}
